from crewai import Agent, Task, Crew, LLM

# ============================================================
# zero-cloud-dev-stack — CrewAI Coder + Auditor Script
# https://github.com/Cipher-rlx/zero-cloud-dev-stack
# ============================================================
# Requirements:
#   - Ollama running with qwen2.5-coder:32b and qwen2.5-coder:7b
#   - Python 3.11 environment: C:\crew-env
#   - Run: C:\crew-env\Scripts\python.exe crew_local.py
# ============================================================

# Connect to local Ollama
llm_large = LLM(
    model="ollama/qwen2.5-coder:32b",
    base_url="http://localhost:11434"
)

llm_fast = LLM(
    model="ollama/qwen2.5-coder:7b",
    base_url="http://localhost:11434"
)

# Agent 1: The Coder (uses the 32B model)
coder = Agent(
    role='Senior Python Developer',
    goal='Write efficient, clean code without inventing non-existent libraries',
    backstory=(
        'You are a Python expert with 10 years of experience. '
        'You only deliver executable code with real, verified imports. '
        'You never invent library names or functions that do not exist.'
    ),
    llm=llm_large,
    verbose=True
)

# Agent 2: The Auditor (uses the 7B model — fast and skeptical)
auditor = Agent(
    role='QA and Security Auditor',
    goal='Detect bugs, invented libraries, and security issues in generated code',
    backstory=(
        'You are skeptical by nature. '
        'If the code imports something that does not exist, you reject it. '
        'You verify every import, check for logic errors, and flag security issues.'
    ),
    llm=llm_fast,
    verbose=True
)

# Task 1: Generate code
task_code = Task(
    description=(
        'Write an async Python function to process a large CSV file with pandas. '
        'The function should: read the file in chunks, filter rows where "status" == "active", '
        'and save the result to a new CSV. Include proper error handling.'
    ),
    expected_output='Clean Python code in a markdown block with all imports included.',
    agent=coder
)

# Task 2: Audit the generated code
task_audit = Task(
    description=(
        'Review the code generated by the developer. '
        'Verify that: all imports are real Python libraries, '
        'there are no obvious bugs or logic errors, '
        'the async usage is correct, and error handling is proper.'
    ),
    expected_output=(
        'Either "APPROVED" with brief comments, '
        'or "NEEDS REVISION" with a specific list of corrections needed.'
    ),
    agent=auditor
)

# Sequential process — one agent at a time, doesn't saturate RAM
crew = Crew(
    agents=[coder, auditor],
    tasks=[task_code, task_audit],
    process='sequential',
    verbose=True
)

if __name__ == '__main__':
    print("\n" + "="*60)
    print("zero-cloud-dev-stack — CrewAI Coder + Auditor")
    print("="*60 + "\n")
    
    result = crew.kickoff()
    
    print("\n" + "="*60)
    print("FINAL RESULT")
    print("="*60)
    print(result)
